package apigen

// client.go renders internal/api/client/client.go: the generated Go
// client with one method per route, all driven through one
// dial-and-request path. The shape follows internal/generate — a
// template with sentinels, gofmt-clean by construction via
// format.Source — and the rendered file depends on the standard library
// and the api package alone, so the runtime dependency list stays at
// exactly two (PLAN-SCOPE.md, "Behaviours").

import (
	"fmt"
	"go/format"
	"strings"

	"github.com/tinkerindustries/worktree-manager/internal/api"
)

// Client renders internal/api/client/client.go. The returned bytes are
// the whole file, deterministic across runs.
func Client() ([]byte, error) {
	docs, err := loadDocs()
	if err != nil {
		return nil, err
	}
	var b strings.Builder
	b.WriteString(clientHeader)
	for _, r := range api.Routes {
		vt, err := verbTypeFor(r.Verb)
		if err != nil {
			return nil, err
		}
		b.WriteString(methodSource(r, vt, docs))
	}
	out, err := format.Source([]byte(b.String()))
	if err != nil {
		return nil, fmt.Errorf("apigen: the rendered client does not parse: %w", err)
	}
	return out, nil
}

// methodSource renders one route's client method. The doc comment is the
// args type's first paragraph (the result type's for a verb that sends
// no arguments), so the method says what the RPC is for.
func methodSource(r api.Route, vt verbType, docs *docIndex) string {
	doc := ""
	if vt.args != nil {
		doc = typeDescription(docs, vt.args)
	}
	if doc == "" {
		doc = typeDescription(docs, vt.result)
	}
	if doc != "" {
		doc = ": " + doc
	}
	repl := map[string]string{
		"@@NAME@@":   methodName(r.Verb),
		"@@VERB@@":   r.Verb,
		"@@METHOD@@": r.Method,
		"@@PATH@@":   r.Path,
		"@@RESULT@@": vt.result.Name(),
		"@@DOC@@":    doc,
	}
	tpl := methodTemplate
	if vt.args == nil {
		tpl = methodNoArgsTemplate
	} else {
		repl["@@ARGS@@"] = vt.args.Name()
	}
	for k, v := range repl {
		tpl = strings.ReplaceAll(tpl, k, v)
	}
	return tpl
}

// clientHeader is the generated file's fixed half: the package
// declaration, the error type, the client and its one dial-and-request
// path, and the Version method (the one response that is not the
// Response envelope).
const clientHeader = `// Code generated by wtgen (worktree-manager, phase R2). DO NOT EDIT.
//
// Package client is the generated HTTP client for the coordinator API:
// one method per route of internal/api.Routes, all driven through one
// dial-and-request path. It is generated from the route table and the
// api *Args/*Result types — the Go types are the single source of truth
// — and a verb added to the table without regenerating fails the build's
// drift checks (plan.md §5, phase R2).
//
// The client never retries and its transport sets Proxy: nil — the
// coordinator's bearer token must never reach a proxy (plan.md §7). The
// response body is authoritative for the exit code: codes 3 and 4 come
// from the envelope's error; code 5 is client-side only, a transport
// failure, and is never derived from an HTTP status.
package client

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"net/http"

	"github.com/tinkerindustries/worktree-manager/internal/api"
)

// Error is one failed request: a response error mapped verbatim from
// the envelope — codes 3 and 4 reach the process exit status unchanged —
// or a client-side failure with Code 5, a transport failure that is
// never derived from an HTTP status (the response body is authoritative
// for the exit code; plan.md §5, phase R1).
type Error struct {
	Code   int
	Msg    string
	Remedy string
}

// Error implements error.
func (e *Error) Error() string { return e.Msg }

// Client is the generated coordinator client: the base URL, the bearer
// token the next request presents, and the one HTTP client everything
// goes through.
type Client struct {
	base  string
	token string
	http  *http.Client
}

// New returns a client for the coordinator at base, presenting bearer
// token on every request. The transport is explicitly constructed with
// Proxy: nil — http.DefaultTransport honours HTTP_PROXY/HTTPS_PROXY, and
// the coordinator's bearer token must never be sent to a proxy (plan.md
// §7). The client never retries: a retried allocate double-allocates, so
// every transport failure is reported once (PLAN-SCOPE.md non-goal 4).
func New(base, token string) *Client {
	return &Client{
		base:  base,
		token: token,
		http:  &http.Client{Transport: &http.Transport{Proxy: nil}},
	}
}

// SetToken replaces the bearer the next request presents. The session
// admission is the one exchange that runs with a different bearer: an
// ephemeral client presents the container token once and receives a
// session id, which becomes its bearer from then on (plan.md §5, phase
// R1).
func (c *Client) SetToken(token string) { c.token = token }

// HTTP returns the underlying *http.Client, exposed so the transport
// rails — Proxy: nil, never a retry — can be pinned by tests. Callers
// that only issue requests never need it.
func (c *Client) HTTP() *http.Client { return c.http }

// do is the one dial-and-request path every RPC method goes through:
// the JSON body, the bearer and X-Wt-Client: 1, then the Response
// envelope. A transport failure is code 5, once; a response error maps
// verbatim from the body, and the HTTP status is advisory and never
// consulted.
func (c *Client) do(verb, method, path string, body []byte, result any) *Error {
	req, err := http.NewRequest(method, c.base+path, bytes.NewReader(body))
	if err != nil {
		return &Error{Code: 5, Msg: fmt.Sprintf("building the %s request for %s: %v", verb, c.base, err)}
	}
	if c.token != "" {
		req.Header.Set("Authorization", "Bearer "+c.token)
	}
	req.Header.Set("X-Wt-Client", "1")
	resp, err := c.http.Do(req)
	if err != nil {
		return &Error{Code: 5, Msg: fmt.Sprintf("coordinator unreachable at %s: %v", c.base, err)}
	}
	defer resp.Body.Close()
	data, err := io.ReadAll(resp.Body)
	if err != nil {
		return &Error{Code: 5, Msg: fmt.Sprintf("coordinator at %s closed before the response: %v", c.base, err)}
	}
	var envelope api.Response
	if err := json.Unmarshal(data, &envelope); err != nil {
		return &Error{Code: 5, Msg: fmt.Sprintf("the coordinator at %s did not answer with a JSON response: %v", c.base, err)}
	}
	if envelope.Error != nil {
		return &Error{Code: envelope.Error.Code, Msg: envelope.Error.Msg, Remedy: envelope.Error.Remedy}
	}
	if err := json.Unmarshal(envelope.Result, result); err != nil {
		return &Error{Code: 1, Msg: fmt.Sprintf("decoding the %s response: %v", verb, err), Remedy: "upgrade wt, then re-run"}
	}
	return nil
}

// Version issues GET /version: the coordinator's supported API version
// range — the hello's replacement, and the one response that is not the
// Response envelope, so a mismatched client reads it and refuses with a
// real upgrade message instead of a bare 404. It is unauthenticated but
// still requires X-Wt-Client: 1, like every request.
func (c *Client) Version() (*api.VersionInfo, *Error) {
	req, err := http.NewRequest("GET", c.base+api.VersionPath, nil)
	if err != nil {
		return nil, &Error{Code: 5, Msg: fmt.Sprintf("building the version request for %s: %v", c.base, err)}
	}
	req.Header.Set("X-Wt-Client", "1")
	resp, err := c.http.Do(req)
	if err != nil {
		return nil, &Error{Code: 5, Msg: fmt.Sprintf("coordinator unreachable at %s: %v", c.base, err)}
	}
	defer resp.Body.Close()
	data, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, &Error{Code: 5, Msg: fmt.Sprintf("coordinator at %s closed before the version report: %v", c.base, err)}
	}
	// A refusal reaches this endpoint too — the Host check and the
	// X-Wt-Client requirement gate it like every other route — and its body
	// is the Response envelope, not a version range. It must be returned as
	// itself: an error envelope decodes into VersionInfo without complaint,
	// leaving the zero range, and the caller would then report a version
	// mismatch against a coordinator whose version was never read.
	var envelope api.Response
	if err := json.Unmarshal(data, &envelope); err == nil && envelope.Error != nil {
		return nil, &Error{Code: envelope.Error.Code, Msg: envelope.Error.Msg, Remedy: envelope.Error.Remedy}
	}
	var info api.VersionInfo
	if err := json.Unmarshal(data, &info); err != nil {
		return nil, &Error{Code: 5, Msg: fmt.Sprintf("the coordinator at %s did not answer /version with a version range: %v", c.base, err)}
	}
	// A range with no maximum is not a range. Something answered on this
	// address that is not a coordinator; saying so beats reporting an
	// overlap failure against 0..0.
	if info.Max == 0 {
		return nil, &Error{Code: 5, Msg: fmt.Sprintf("the coordinator at %s answered /version with no version range; something that is not wtd is listening there", c.base)}
	}
	return &info, nil
}

`

// methodTemplate is one route's client method with a typed args
// parameter: marshal the args, send, decode into the typed result.
const methodTemplate = `
// @@NAME@@ issues @@METHOD@@ @@PATH@@@@DOC@@
func (c *Client) @@NAME@@(args *api.@@ARGS@@) (*api.@@RESULT@@, *Error) {
	var result api.@@RESULT@@
	body, err := json.Marshal(args)
	if err != nil {
		return nil, &Error{Code: 1, Msg: fmt.Sprintf("encoding the @@VERB@@ request: %v", err), Remedy: "check the wt build, then re-run"}
	}
	if err := c.do("@@VERB@@", "@@METHOD@@", "@@PATH@@", body, &result); err != nil {
		return nil, err
	}
	return &result, nil
}
`

// methodNoArgsTemplate is one route's client method for a verb whose
// request carries no arguments: the client sends an empty object.
const methodNoArgsTemplate = `
// @@NAME@@ issues @@METHOD@@ @@PATH@@@@DOC@@
func (c *Client) @@NAME@@() (*api.@@RESULT@@, *Error) {
	var result api.@@RESULT@@
	if err := c.do("@@VERB@@", "@@METHOD@@", "@@PATH@@", []byte("{}"), &result); err != nil {
		return nil, err
	}
	return &result, nil
}
`
