// Code generated by wtgen (worktree-manager, phase R2). DO NOT EDIT.
//
// Package client is the generated HTTP client for the coordinator API:
// one method per route of internal/api.Routes, all driven through one
// dial-and-request path. It is generated from the route table and the
// api *Args/*Result types — the Go types are the single source of truth
// — and a verb added to the table without regenerating fails the build's
// drift checks (plan.md §5, phase R2).
//
// The client never retries and its transport sets Proxy: nil — the
// coordinator's bearer token must never reach a proxy (plan.md §7). The
// response body is authoritative for the exit code: codes 3 and 4 come
// from the envelope's error; code 5 is client-side only, a transport
// failure, and is never derived from an HTTP status.
package client

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"net/http"

	"github.com/mrgeoffrich/worktree-manager/internal/api"
)

// Error is one failed request: a response error mapped verbatim from
// the envelope — codes 3 and 4 reach the process exit status unchanged —
// or a client-side failure with Code 5, a transport failure that is
// never derived from an HTTP status (the response body is authoritative
// for the exit code; plan.md §5, phase R1).
type Error struct {
	Code   int
	Msg    string
	Remedy string
}

// Error implements error.
func (e *Error) Error() string { return e.Msg }

// Client is the generated coordinator client: the base URL, the bearer
// token the next request presents, and the one HTTP client everything
// goes through.
type Client struct {
	base  string
	token string
	http  *http.Client
}

// New returns a client for the coordinator at base, presenting bearer
// token on every request. The transport is explicitly constructed with
// Proxy: nil — http.DefaultTransport honours HTTP_PROXY/HTTPS_PROXY, and
// the coordinator's bearer token must never be sent to a proxy (plan.md
// §7). The client never retries: a retried allocate double-allocates, so
// every transport failure is reported once (PLAN-SCOPE.md non-goal 4).
func New(base, token string) *Client {
	return &Client{
		base:  base,
		token: token,
		http:  &http.Client{Transport: &http.Transport{Proxy: nil}},
	}
}

// SetToken replaces the bearer the next request presents. The session
// admission is the one exchange that runs with a different bearer: an
// ephemeral client presents the container token once and receives a
// session id, which becomes its bearer from then on (plan.md §5, phase
// R1).
func (c *Client) SetToken(token string) { c.token = token }

// HTTP returns the underlying *http.Client, exposed so the transport
// rails — Proxy: nil, never a retry — can be pinned by tests. Callers
// that only issue requests never need it.
func (c *Client) HTTP() *http.Client { return c.http }

// do is the one dial-and-request path every RPC method goes through:
// the JSON body, the bearer and X-Wt-Client: 1, then the Response
// envelope. A transport failure is code 5, once; a response error maps
// verbatim from the body, and the HTTP status is advisory and never
// consulted.
func (c *Client) do(verb, method, path string, body []byte, result any) *Error {
	req, err := http.NewRequest(method, c.base+path, bytes.NewReader(body))
	if err != nil {
		return &Error{Code: 5, Msg: fmt.Sprintf("building the %s request for %s: %v", verb, c.base, err)}
	}
	if c.token != "" {
		req.Header.Set("Authorization", "Bearer "+c.token)
	}
	req.Header.Set("X-Wt-Client", "1")
	resp, err := c.http.Do(req)
	if err != nil {
		return &Error{Code: 5, Msg: fmt.Sprintf("coordinator unreachable at %s: %v", c.base, err)}
	}
	defer resp.Body.Close()
	data, err := io.ReadAll(resp.Body)
	if err != nil {
		return &Error{Code: 5, Msg: fmt.Sprintf("coordinator at %s closed before the response: %v", c.base, err)}
	}
	var envelope api.Response
	if err := json.Unmarshal(data, &envelope); err != nil {
		return &Error{Code: 5, Msg: fmt.Sprintf("the coordinator at %s did not answer with a JSON response: %v", c.base, err)}
	}
	if envelope.Error != nil {
		return &Error{Code: envelope.Error.Code, Msg: envelope.Error.Msg, Remedy: envelope.Error.Remedy}
	}
	if err := json.Unmarshal(envelope.Result, result); err != nil {
		return &Error{Code: 1, Msg: fmt.Sprintf("decoding the %s response: %v", verb, err), Remedy: "upgrade wt, then re-run"}
	}
	return nil
}

// Version issues GET /version: the coordinator's supported API version
// range — the hello's replacement, and the one response that is not the
// Response envelope, so a mismatched client reads it and refuses with a
// real upgrade message instead of a bare 404. It is unauthenticated but
// still requires X-Wt-Client: 1, like every request.
func (c *Client) Version() (*api.VersionInfo, *Error) {
	req, err := http.NewRequest("GET", c.base+api.VersionPath, nil)
	if err != nil {
		return nil, &Error{Code: 5, Msg: fmt.Sprintf("building the version request for %s: %v", c.base, err)}
	}
	req.Header.Set("X-Wt-Client", "1")
	resp, err := c.http.Do(req)
	if err != nil {
		return nil, &Error{Code: 5, Msg: fmt.Sprintf("coordinator unreachable at %s: %v", c.base, err)}
	}
	defer resp.Body.Close()
	data, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, &Error{Code: 5, Msg: fmt.Sprintf("coordinator at %s closed before the version report: %v", c.base, err)}
	}
	// A refusal reaches this endpoint too — the Host check and the
	// X-Wt-Client requirement gate it like every other route — and its body
	// is the Response envelope, not a version range. It must be returned as
	// itself: an error envelope decodes into VersionInfo without complaint,
	// leaving the zero range, and the caller would then report a version
	// mismatch against a coordinator whose version was never read.
	var envelope api.Response
	if err := json.Unmarshal(data, &envelope); err == nil && envelope.Error != nil {
		return nil, &Error{Code: envelope.Error.Code, Msg: envelope.Error.Msg, Remedy: envelope.Error.Remedy}
	}
	var info api.VersionInfo
	if err := json.Unmarshal(data, &info); err != nil {
		return nil, &Error{Code: 5, Msg: fmt.Sprintf("the coordinator at %s did not answer /version with a version range: %v", c.base, err)}
	}
	// A range with no maximum is not a range. Something answered on this
	// address that is not a coordinator; saying so beats reporting an
	// overlap failure against 0..0.
	if info.Max == 0 {
		return nil, &Error{Code: 5, Msg: fmt.Sprintf("the coordinator at %s answered /version with no version range; something that is not wtd is listening there", c.base)}
	}
	return &info, nil
}

// Session issues POST /v1/session: SessionResult is the POST /v1/session response: the issued ephemeral session id.
func (c *Client) Session() (*api.SessionResult, *Error) {
	var result api.SessionResult
	if err := c.do("session", "POST", "/v1/session", []byte("{}"), &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Allocate issues POST /v1/allocate: AllocateArgs is the allocate request: the parsed spec (the client sends the spec with each call — ARCHITECTURE.md §8.1), the slug, the path as the creating client saw it, where the descriptor went, the ten-words-or-fewer description, and the seed credentials recorded for the owning client alone.
func (c *Client) Allocate(args *api.AllocateArgs) (*api.AllocateResult, *Error) {
	var result api.AllocateResult
	body, err := json.Marshal(args)
	if err != nil {
		return nil, &Error{Code: 1, Msg: fmt.Sprintf("encoding the allocate request: %v", err), Remedy: "check the wt build, then re-run"}
	}
	if err := c.do("allocate", "POST", "/v1/allocate", body, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Materialise issues POST /v1/materialise: MaterialiseArgs is the materialise request: the spec and the entry whose resources are applied in dependency order.
func (c *Client) Materialise(args *api.MaterialiseArgs) (*api.MaterialiseResult, *Error) {
	var result api.MaterialiseResult
	body, err := json.Marshal(args)
	if err != nil {
		return nil, &Error{Code: 1, Msg: fmt.Sprintf("encoding the materialise request: %v", err), Remedy: "check the wt build, then re-run"}
	}
	if err := c.do("materialise", "POST", "/v1/materialise", body, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Activate issues POST /v1/activate: EntryRef names one registry entry: the app and slug pair that identifies it. Mutating calls against it run the ownership check (ARCHITECTURE.md §4.3, §8.6 rule 6).
func (c *Client) Activate(args *api.EntryRef) (*api.ActivateResult, *Error) {
	var result api.ActivateResult
	body, err := json.Marshal(args)
	if err != nil {
		return nil, &Error{Code: 1, Msg: fmt.Sprintf("encoding the activate request: %v", err), Remedy: "check the wt build, then re-run"}
	}
	if err := c.do("activate", "POST", "/v1/activate", body, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Release issues POST /v1/release: EntryRef names one registry entry: the app and slug pair that identifies it. Mutating calls against it run the ownership check (ARCHITECTURE.md §4.3, §8.6 rule 6).
func (c *Client) Release(args *api.EntryRef) (*api.ReleaseResult, *Error) {
	var result api.ReleaseResult
	body, err := json.Marshal(args)
	if err != nil {
		return nil, &Error{Code: 1, Msg: fmt.Sprintf("encoding the release request: %v", err), Remedy: "check the wt build, then re-run"}
	}
	if err := c.do("release", "POST", "/v1/release", body, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Rm issues POST /v1/rm: RmArgs is the rm request: the entry (app, slug), the spec (teardown needs it for the dependent projects and the purge refusal), whether the reaper is opted out, whether this is a preview, and the CLI purge flags.
func (c *Client) Rm(args *api.RmArgs) (*api.RmResult, *Error) {
	var result api.RmResult
	body, err := json.Marshal(args)
	if err != nil {
		return nil, &Error{Code: 1, Msg: fmt.Sprintf("encoding the rm request: %v", err), Remedy: "check the wt build, then re-run"}
	}
	if err := c.do("rm", "POST", "/v1/rm", body, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// BandsReserve issues POST /v1/bands/reserve: ReserveBandArgs is the bands.reserve request. Two forms, mutually exclusive. App mode carries the parsed spec and one base per port resource, so the coordinator can compute the band's required size from the spec — the onboarding skill chooses only where the bases sit, not how large they are (02-coordination.md §6.2). Host mode carries the ports no app may allocate from, the compose project names no teardown may reach, and the required note naming what holds the range (plan.md §8, R6): nothing infers a production stack, a person declares it once per machine.
func (c *Client) BandsReserve(args *api.ReserveBandArgs) (*api.ReserveBandResult, *Error) {
	var result api.ReserveBandResult
	body, err := json.Marshal(args)
	if err != nil {
		return nil, &Error{Code: 1, Msg: fmt.Sprintf("encoding the bands.reserve request: %v", err), Remedy: "check the wt build, then re-run"}
	}
	if err := c.do("bands.reserve", "POST", "/v1/bands/reserve", body, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// BandsList issues POST /v1/bands/list: BandsListResult is the whole ledger: the app bands and the machine-wide reservations.
func (c *Client) BandsList() (*api.BandsListResult, *Error) {
	var result api.BandsListResult
	if err := c.do("bands.list", "POST", "/v1/bands/list", []byte("{}"), &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// BandsSuggest issues POST /v1/bands/suggest: SuggestBandArgs is the bands.suggest request: the spec whose port resources need bases. The client sends the parsed spec exactly as bands.reserve does — the coordinator computes the required size from it and proposes where the bases could sit against the current ledger.
func (c *Client) BandsSuggest(args *api.SuggestBandArgs) (*api.SuggestBandResult, *Error) {
	var result api.SuggestBandResult
	body, err := json.Marshal(args)
	if err != nil {
		return nil, &Error{Code: 1, Msg: fmt.Sprintf("encoding the bands.suggest request: %v", err), Remedy: "check the wt build, then re-run"}
	}
	if err := c.do("bands.suggest", "POST", "/v1/bands/suggest", body, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// PortsScan issues POST /v1/ports/scan: PortsScanResult is the whole scan: the listeners sorted by port, plus the bounded-coverage notes — what the scan could not see and why (a silent degrade reads as success, plan.md §3).
func (c *Client) PortsScan() (*api.PortsScanResult, *Error) {
	var result api.PortsScanResult
	if err := c.do("ports.scan", "POST", "/v1/ports/scan", []byte("{}"), &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// List issues POST /v1/list: ListArgs is the list request. Wide asks for the owning client's seed credentials — served to the owning client alone and redacted for every other client either way (ARCHITECTURE.md §12.2): a --wide form may show them to the owner, never to anyone else.
func (c *Client) List(args *api.ListArgs) (*api.ListResult, *Error) {
	var result api.ListResult
	body, err := json.Marshal(args)
	if err != nil {
		return nil, &Error{Code: 1, Msg: fmt.Sprintf("encoding the list request: %v", err), Remedy: "check the wt build, then re-run"}
	}
	if err := c.do("list", "POST", "/v1/list", body, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Doctor issues POST /v1/doctor: DoctorResult is the whole report: the findings plus the bounded-coverage notes — what doctor could not check and why (a silent degrade reads as success, plan.md §3).
func (c *Client) Doctor() (*api.DoctorResult, *Error) {
	var result api.DoctorResult
	if err := c.do("doctor", "POST", "/v1/doctor", []byte("{}"), &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Reconcile issues POST /v1/reconcile: ReconcileArgs is the reconcile request: the app, the spec (reap and teardown need it, exactly as rm does), and the refs the caller believes are its own or reclaimable. The coordinator re-checks every ref against the ownership and aged-out rules — the caller's claim is never trusted.
func (c *Client) Reconcile(args *api.ReconcileArgs) (*api.ReconcileResult, *Error) {
	var result api.ReconcileResult
	body, err := json.Marshal(args)
	if err != nil {
		return nil, &Error{Code: 1, Msg: fmt.Sprintf("encoding the reconcile request: %v", err), Remedy: "check the wt build, then re-run"}
	}
	if err := c.do("reconcile", "POST", "/v1/reconcile", body, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// ClientsList issues POST /v1/clients/list: ClientsListResult is the whole client table.
func (c *Client) ClientsList() (*api.ClientsListResult, *Error) {
	var result api.ClientsListResult
	if err := c.do("clients.list", "POST", "/v1/clients/list", []byte("{}"), &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Ping issues GET /v1/ping: PingResult is the GET /v1/ping response: the wire's one plumbing verb answers with a fixed success object — a full request round trip with nothing behind it. Phase R2 gives it a real type so the described API can derive its schema like every other result, instead of the raw literal the transport used to emit.
func (c *Client) Ping() (*api.PingResult, *Error) {
	var result api.PingResult
	if err := c.do("ping", "GET", "/v1/ping", []byte("{}"), &result); err != nil {
		return nil, err
	}
	return &result, nil
}
