// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"database/sql"
)

type BandRow struct {
	App      string
	Resource string
	Base     int64
	Span     int64
}

type ClientRow struct {
	Identity  string
	Kind      string
	LastSeen  string
	Ephemeral int64
}

type EntryRow struct {
	App            string
	Slug           string
	Slot           int64
	Owner          string
	OwnerKind      string
	Ephemeral      int64
	Path           string
	PathVisible    int64
	State          string
	TeardownNote   sql.NullString
	Resources      string
	Secrets        sql.NullString
	DescriptorPath sql.NullString
	Description    sql.NullString
	CreatedAt      string
	LastSeen       string
}

type MetaRow struct {
	Key   string
	Value string
}

type ReservationNameRow struct {
	ReservationID int64
	Name          string
}

type ReservationPortRow struct {
	ReservationID int64
	Port          int64
}

type ReservationRow struct {
	ID   int64
	Note string
}

type SpecRow struct {
	App     string
	SpecRow string
}
