// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package store

import (
	"context"
	"database/sql"
)

const addReservation = `-- name: AddReservation :execresult
INSERT INTO reservations (note) VALUES (?)
`

func (q *Queries) AddReservation(ctx context.Context, note string) (sql.Result, error) {
	return q.db.ExecContext(ctx, addReservation, note)
}

const addReservationName = `-- name: AddReservationName :exec
INSERT INTO reservation_names (reservation_id, name) VALUES (?, ?)
`

type AddReservationNameParams struct {
	ReservationID int64
	Name          string
}

func (q *Queries) AddReservationName(ctx context.Context, arg AddReservationNameParams) error {
	_, err := q.db.ExecContext(ctx, addReservationName, arg.ReservationID, arg.Name)
	return err
}

const addReservationPort = `-- name: AddReservationPort :exec
INSERT INTO reservation_ports (reservation_id, port) VALUES (?, ?)
`

type AddReservationPortParams struct {
	ReservationID int64
	Port          int64
}

func (q *Queries) AddReservationPort(ctx context.Context, arg AddReservationPortParams) error {
	_, err := q.db.ExecContext(ctx, addReservationPort, arg.ReservationID, arg.Port)
	return err
}

const deleteBandApp = `-- name: DeleteBandApp :exec
DELETE FROM bands WHERE app = ?
`

func (q *Queries) DeleteBandApp(ctx context.Context, app string) error {
	_, err := q.db.ExecContext(ctx, deleteBandApp, app)
	return err
}

const deleteClient = `-- name: DeleteClient :exec
DELETE FROM clients WHERE identity = ? AND kind = ?
`

type DeleteClientParams struct {
	Identity string
	Kind     string
}

func (q *Queries) DeleteClient(ctx context.Context, arg DeleteClientParams) error {
	_, err := q.db.ExecContext(ctx, deleteClient, arg.Identity, arg.Kind)
	return err
}

const deleteEntry = `-- name: DeleteEntry :exec
DELETE FROM entries WHERE app = ? AND slug = ?
`

type DeleteEntryParams struct {
	App  string
	Slug string
}

func (q *Queries) DeleteEntry(ctx context.Context, arg DeleteEntryParams) error {
	_, err := q.db.ExecContext(ctx, deleteEntry, arg.App, arg.Slug)
	return err
}

const deleteSpec = `-- name: DeleteSpec :exec
DELETE FROM specs WHERE app = ?
`

func (q *Queries) DeleteSpec(ctx context.Context, app string) error {
	_, err := q.db.ExecContext(ctx, deleteSpec, app)
	return err
}

const getEntry = `-- name: GetEntry :one
SELECT app, slug, slot, owner, owner_kind, ephemeral, path, path_visible,
       state, teardown_note, resources, secrets, descriptor_path, description,
       created_at, last_seen
FROM entries
WHERE app = ? AND slug = ?
`

type GetEntryParams struct {
	App  string
	Slug string
}

func (q *Queries) GetEntry(ctx context.Context, arg GetEntryParams) (EntryRow, error) {
	row := q.db.QueryRowContext(ctx, getEntry, arg.App, arg.Slug)
	var i EntryRow
	err := row.Scan(
		&i.App,
		&i.Slug,
		&i.Slot,
		&i.Owner,
		&i.OwnerKind,
		&i.Ephemeral,
		&i.Path,
		&i.PathVisible,
		&i.State,
		&i.TeardownNote,
		&i.Resources,
		&i.Secrets,
		&i.DescriptorPath,
		&i.Description,
		&i.CreatedAt,
		&i.LastSeen,
	)
	return i, err
}

const getMeta = `-- name: GetMeta :one

SELECT value FROM meta WHERE key = ?
`

// Query file for the coordinator's SQLite store. The generated Go is
// committed and sqlc is a build-time tool (go.mod `tool` directive); the
// wrappers in this package convert between these rows and the public store
// types (Entry, Band, ClientEntry, ...). One writer serialises in the
// coordinator (the Handler mutex); these are the statements underneath it.
func (q *Queries) GetMeta(ctx context.Context, key string) (string, error) {
	row := q.db.QueryRowContext(ctx, getMeta, key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const listBands = `-- name: ListBands :many
SELECT app, resource, base, span FROM bands ORDER BY app, resource
`

func (q *Queries) ListBands(ctx context.Context) ([]BandRow, error) {
	rows, err := q.db.QueryContext(ctx, listBands)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BandRow{}
	for rows.Next() {
		var i BandRow
		if err := rows.Scan(
			&i.App,
			&i.Resource,
			&i.Base,
			&i.Span,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClients = `-- name: ListClients :many
SELECT identity, kind, last_seen, ephemeral FROM clients ORDER BY kind, identity
`

func (q *Queries) ListClients(ctx context.Context) ([]ClientRow, error) {
	rows, err := q.db.QueryContext(ctx, listClients)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClientRow{}
	for rows.Next() {
		var i ClientRow
		if err := rows.Scan(
			&i.Identity,
			&i.Kind,
			&i.LastSeen,
			&i.Ephemeral,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntries = `-- name: ListEntries :many
SELECT app, slug, slot, owner, owner_kind, ephemeral, path, path_visible,
       state, teardown_note, resources, secrets, descriptor_path, description,
       created_at, last_seen
FROM entries
ORDER BY app, slug
`

func (q *Queries) ListEntries(ctx context.Context) ([]EntryRow, error) {
	rows, err := q.db.QueryContext(ctx, listEntries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EntryRow{}
	for rows.Next() {
		var i EntryRow
		if err := rows.Scan(
			&i.App,
			&i.Slug,
			&i.Slot,
			&i.Owner,
			&i.OwnerKind,
			&i.Ephemeral,
			&i.Path,
			&i.PathVisible,
			&i.State,
			&i.TeardownNote,
			&i.Resources,
			&i.Secrets,
			&i.DescriptorPath,
			&i.Description,
			&i.CreatedAt,
			&i.LastSeen,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReservationNames = `-- name: ListReservationNames :many
SELECT reservation_id, name FROM reservation_names ORDER BY reservation_id, name
`

func (q *Queries) ListReservationNames(ctx context.Context) ([]ReservationNameRow, error) {
	rows, err := q.db.QueryContext(ctx, listReservationNames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReservationNameRow{}
	for rows.Next() {
		var i ReservationNameRow
		if err := rows.Scan(&i.ReservationID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReservationPorts = `-- name: ListReservationPorts :many
SELECT reservation_id, port FROM reservation_ports ORDER BY reservation_id, port
`

func (q *Queries) ListReservationPorts(ctx context.Context) ([]ReservationPortRow, error) {
	rows, err := q.db.QueryContext(ctx, listReservationPorts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReservationPortRow{}
	for rows.Next() {
		var i ReservationPortRow
		if err := rows.Scan(&i.ReservationID, &i.Port); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReservations = `-- name: ListReservations :many
SELECT id, note FROM reservations ORDER BY id
`

func (q *Queries) ListReservations(ctx context.Context) ([]ReservationRow, error) {
	rows, err := q.db.QueryContext(ctx, listReservations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReservationRow{}
	for rows.Next() {
		var i ReservationRow
		if err := rows.Scan(&i.ID, &i.Note); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSpecs = `-- name: ListSpecs :many
SELECT app, spec FROM specs ORDER BY app
`

func (q *Queries) ListSpecs(ctx context.Context) ([]Spec, error) {
	rows, err := q.db.QueryContext(ctx, listSpecs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Spec{}
	for rows.Next() {
		var i Spec
		if err := rows.Scan(&i.App, &i.Spec); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setMeta = `-- name: SetMeta :exec
INSERT INTO meta (key, value) VALUES (?, ?)
ON CONFLICT(key) DO UPDATE SET value = excluded.value
`

type SetMetaParams struct {
	Key   string
	Value string
}

func (q *Queries) SetMeta(ctx context.Context, arg SetMetaParams) error {
	_, err := q.db.ExecContext(ctx, setMeta, arg.Key, arg.Value)
	return err
}

const touchEntry = `-- name: TouchEntry :exec
UPDATE entries SET last_seen = ? WHERE app = ? AND slug = ?
`

type TouchEntryParams struct {
	LastSeen string
	App      string
	Slug     string
}

func (q *Queries) TouchEntry(ctx context.Context, arg TouchEntryParams) error {
	_, err := q.db.ExecContext(ctx, touchEntry, arg.LastSeen, arg.App, arg.Slug)
	return err
}

const updateEntryState = `-- name: UpdateEntryState :exec
UPDATE entries SET state = ?, teardown_note = ? WHERE app = ? AND slug = ?
`

type UpdateEntryStateParams struct {
	State        string
	TeardownNote sql.NullString
	App          string
	Slug         string
}

func (q *Queries) UpdateEntryState(ctx context.Context, arg UpdateEntryStateParams) error {
	_, err := q.db.ExecContext(ctx, updateEntryState,
		arg.State,
		arg.TeardownNote,
		arg.App,
		arg.Slug,
	)
	return err
}

const upsertBand = `-- name: UpsertBand :exec
INSERT INTO bands (app, resource, base, span) VALUES (?, ?, ?, ?)
ON CONFLICT(app, resource) DO UPDATE SET base = excluded.base, span = excluded.span
`

type UpsertBandParams struct {
	App      string
	Resource string
	Base     int64
	Span     int64
}

func (q *Queries) UpsertBand(ctx context.Context, arg UpsertBandParams) error {
	_, err := q.db.ExecContext(ctx, upsertBand,
		arg.App,
		arg.Resource,
		arg.Base,
		arg.Span,
	)
	return err
}

const upsertClient = `-- name: UpsertClient :exec
INSERT INTO clients (identity, kind, last_seen, ephemeral) VALUES (?, ?, ?, ?)
ON CONFLICT(identity, kind) DO UPDATE SET last_seen = excluded.last_seen, ephemeral = excluded.ephemeral
`

type UpsertClientParams struct {
	Identity  string
	Kind      string
	LastSeen  string
	Ephemeral int64
}

func (q *Queries) UpsertClient(ctx context.Context, arg UpsertClientParams) error {
	_, err := q.db.ExecContext(ctx, upsertClient,
		arg.Identity,
		arg.Kind,
		arg.LastSeen,
		arg.Ephemeral,
	)
	return err
}

const upsertEntry = `-- name: UpsertEntry :exec
INSERT INTO entries (app, slug, slot, owner, owner_kind, ephemeral, path,
                     path_visible, state, teardown_note, resources, secrets,
                     descriptor_path, description, created_at, last_seen)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(app, slug) DO UPDATE SET
  slot = excluded.slot,
  owner = excluded.owner,
  owner_kind = excluded.owner_kind,
  ephemeral = excluded.ephemeral,
  path = excluded.path,
  path_visible = excluded.path_visible,
  state = excluded.state,
  teardown_note = excluded.teardown_note,
  resources = excluded.resources,
  secrets = excluded.secrets,
  descriptor_path = excluded.descriptor_path,
  description = excluded.description,
  created_at = excluded.created_at,
  last_seen = excluded.last_seen
`

type UpsertEntryParams struct {
	App            string
	Slug           string
	Slot           int64
	Owner          string
	OwnerKind      string
	Ephemeral      int64
	Path           string
	PathVisible    int64
	State          string
	TeardownNote   sql.NullString
	Resources      string
	Secrets        sql.NullString
	DescriptorPath sql.NullString
	Description    sql.NullString
	CreatedAt      string
	LastSeen       string
}

func (q *Queries) UpsertEntry(ctx context.Context, arg UpsertEntryParams) error {
	_, err := q.db.ExecContext(ctx, upsertEntry,
		arg.App,
		arg.Slug,
		arg.Slot,
		arg.Owner,
		arg.OwnerKind,
		arg.Ephemeral,
		arg.Path,
		arg.PathVisible,
		arg.State,
		arg.TeardownNote,
		arg.Resources,
		arg.Secrets,
		arg.DescriptorPath,
		arg.Description,
		arg.CreatedAt,
		arg.LastSeen,
	)
	return err
}

const upsertSpec = `-- name: UpsertSpec :exec
INSERT INTO specs (app, spec) VALUES (?, ?)
ON CONFLICT(app) DO UPDATE SET spec = excluded.spec
`

type UpsertSpecParams struct {
	App  string
	Spec string
}

func (q *Queries) UpsertSpec(ctx context.Context, arg UpsertSpecParams) error {
	_, err := q.db.ExecContext(ctx, upsertSpec, arg.App, arg.Spec)
	return err
}
