// Package generate produces the generated descriptor reader (05-delivery.md
// §4): the Go source an adopted repository compiles into its own entry
// points so the application resolves its environment without the tooling
// present. It is a function another package calls — phase 7's onboarding
// skill, and phase 5's fixture wiring, place the returned source at the
// path the spec declares (emit.reader.path) — never a verb.
//
// Two decisions bind the generated code, both stated here because they are
// the module's contract:
//
//   - The reader depends on the standard library alone. It is copied into
//     someone else's repository, so it cannot add a dependency to that
//     repo's go.mod — in particular it never imports the YAML module this
//     repository uses. A yaml-format descriptor is parsed by a small
//     parser for the exact YAML subset the emitter writes (block mappings,
//     block sequences, quoted and plain scalars — nothing else); anything
//     outside the subset is refused with the line number. The subset is
//     pinned by a generator test that emits a real descriptor and parses
//     it with the generated reader.
//   - The reader reads the descriptor file and nothing else: no registry,
//     no socket, no WT_HOME, no wt binary installed. It finds the
//     committed spec by walking up from cwd to the worktree root, and git
//     (the repo's own tool) tells the primary checkout from a linked
//     worktree. The descriptor's filename, format and app, and the
//     app-scoped env var, are baked from the spec at generation time: the
//     reader is a generated artefact of the spec, regenerated when the
//     spec changes.
package generate

import (
	"fmt"
	"go/format"
	"strings"

	"github.com/mrgeoffrich/worktree-manager/internal/spec"
)

// Reader renders the Go source for the spec's emit.reader section. The
// returned bytes are the whole file: package declaration, the four-row
// resolution, the descriptor readers (yaml subset and json), and the
// status output. The caller writes them to emit.reader.path.
func Reader(s *spec.Spec) ([]byte, error) {
	if s.Emit.Reader == nil {
		return nil, fmt.Errorf("generate: the spec declares no emit.reader; nothing to generate")
	}
	r := s.Emit.Reader
	if r.Language != "go" {
		return nil, fmt.Errorf("generate: reader language %q is not supported; PLAN-SCOPE.md allows go only", r.Language)
	}
	if r.Package == "" {
		return nil, fmt.Errorf("generate: emit.reader.package is required")
	}
	if r.EnvVar == "" {
		return nil, fmt.Errorf("generate: emit.reader.env_var is required — the app-scoped variable that names a descriptor (05-delivery.md §4.1)")
	}

	resourceNames := make([]string, 0, len(s.Resources))
	for i := range s.Resources {
		resourceNames = append(resourceNames, fmt.Sprintf("%q", s.Resources[i].Name))
	}

	out := readerTemplate
	repl := map[string]string{
		"@@PKG@@":       r.Package,
		"@@APP@@":       s.App,
		"@@ENVVAR@@":    r.EnvVar,
		"@@FILENAME@@":  s.Emit.Descriptor.Filename,
		"@@FORMAT@@":    s.Emit.Descriptor.Format,
		"@@RESOURCES@@": strings.Join(resourceNames, ", "),
		"@@BT@@":        "`",
	}
	for k, v := range repl {
		out = strings.ReplaceAll(out, k, v)
	}
	// The generated file is gofmt-clean by construction: it lands in
	// someone else's repository, where it should never be the one file
	// that fails the repo's own fmt check.
	formatted, err := format.Source([]byte(out))
	if err != nil {
		return nil, fmt.Errorf("generate: the rendered reader does not parse: %v", err)
	}
	return formatted, nil
}

// readerTemplate is the generated file. The sentinels are replaced by
// Reader; the body is the contract the fixture test builds and runs, so it
// must stay buildable as-is with every field substituted.
const readerTemplate = `// Code generated by worktree-manager (phase 5, delivery). DO NOT EDIT.
//
// Package @@PKG@@ is the generated descriptor reader for @@APP@@: it
// resolves the application's environment from the worktree descriptor,
// reading nothing but the descriptor and the committed wt.yaml — no
// registry, no socket, no WT_HOME, no wt binary installed — so this
// application can be built and shipped without the tooling present
// (docs/design/05-delivery.md §4).
//
// Precedence, honoured identically by every entry point (§4.1):
//   1. explicit flags — when the caller's values cover every resource,
//      the answer is the caller's own and nothing is read, so a broken
//      override cannot take down an explicit call (B18.2);
//   2. an env override naming a descriptor — the per-invocation --env
//      value beats the @@ENVVAR@@ variable (app-scoped, never WT_ENV);
//   3. the descriptor found from cwd, walking up to the worktree root;
//   4. the legacy default.
//
// Resolution table (§4.3): the committed spec is the adoption signal. No
// spec, or the primary checkout (slot 0 keeps the committed defaults),
// resolves to the legacy default; a linked worktree of an adopted repo
// resolves through the descriptor, and a missing descriptor there refuses
// loudly, naming wt init.
package @@PKG@@

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strconv"
	"strings"
)

const (
	// App is the application this reader was generated for.
	App = "@@APP@@"

	// EnvVar is the app-scoped environment variable that names a
	// descriptor. It is app-scoped, never WT_ENV: one ambient shared name
	// would point every application at one descriptor.
	EnvVar = "@@ENVVAR@@"

	// DescriptorFilename and DescriptorFormat come from the repo's
	// committed spec (emit.descriptor) at generation time. The reader is a
	// generated artefact of the spec: when the spec changes, regenerate
	// the reader.
	DescriptorFilename = "@@FILENAME@@"
	DescriptorFormat   = "@@FORMAT@@"
)

// Source names the winner of the precedence. Env.Source and Env.EnvPath
// are the provenance the status output reports (B18.3), as env_source and
// env_path.
type Source string

const (
	SourceFlags      Source = "flags"
	SourceEnv        Source = "env"
	SourceDescriptor Source = "descriptor"
	SourceLegacy     Source = "legacy"
)

// Env is the resolved application environment: the identity fields, the
// resolved resources, and the provenance.
type Env struct {
	App        string            @@BT@@json:"app"@@BT@@
	Slug       string            @@BT@@json:"slug"@@BT@@
	Slot       int               @@BT@@json:"slot"@@BT@@
	Path       string            @@BT@@json:"path"@@BT@@
	Standalone bool              @@BT@@json:"standalone"@@BT@@
	Resources  map[string]string @@BT@@json:"resources"@@BT@@
	Source     Source            @@BT@@json:"env_source"@@BT@@
	EnvPath    string            @@BT@@json:"env_path,omitempty"@@BT@@
}

// resourceNames is every resource this reader resolves, from the spec's
// resources at generation time. When the caller's explicit values cover
// all of them, the descriptor read is short-circuited entirely.
var resourceNames = []string{@@RESOURCES@@}

// Resolve computes the environment. explicit carries the values the
// application already fixed from its own flags; flagEnvPath is the
// per-invocation --env value, "" when the flag was not given — it beats
// the EnvVar variable.
func Resolve(flagEnvPath string, explicit map[string]string) (Env, error) {
	// 1. Explicit flags: fully supplied means the caller's values are the
	// answer, and nothing is read.
	if fullySupplied(explicit) {
		return Env{Resources: explicit, Source: SourceFlags}, nil
	}
	// 2. An env override naming a descriptor. An override that cannot be
	// honoured is never a fall-through: a missing file is an error.
	envPath := flagEnvPath
	if envPath == "" {
		envPath = os.Getenv(EnvVar)
	}
	if envPath != "" {
		d, err := readDescriptor(envPath)
		if err != nil {
			return Env{}, err
		}
		if d.App != "" && d.App != App {
			return Env{}, fmt.Errorf("%s names app %q, but this reader is for %q: an override pointing at another app's descriptor is refused, never honoured", envPath, d.App, App)
		}
		return d.env(SourceEnv, envPath, explicit), nil
	}
	// 3. The descriptor found from cwd. The walk stops at the worktree
	// root — the first directory with a committed wt.yaml — and never
	// goes above it.
	root, specPath, err := findSpec()
	if err != nil {
		return Env{}, err
	}
	if specPath == "" {
		// The repository has not adopted the tooling: legacy behaviour,
		// byte-identical to running without wt (A3).
		return Env{Source: SourceLegacy}, nil
	}
	// The primary checkout (and a standalone clone, whose git dirs
	// coincide) is slot 0: never managed, keeps the committed defaults.
	if !linkedWorktree(root) {
		return Env{Source: SourceLegacy}, nil
	}
	// A linked worktree of an adopted repo: the descriptor is the answer,
	// and a missing one is drift — a worktree created five minutes ago and
	// one whose descriptor was deleted are equally dangerous to resolve
	// with legacy defaults, because either way the application attaches to
	// the shared store or the committed port and collides with whoever
	// holds slot 0 (§4.3). Refuse, naming the repair.
	dpath := filepath.Join(root, DescriptorFilename)
	if _, err := os.Stat(dpath); err != nil {
		if os.IsNotExist(err) {
			return Env{}, fmt.Errorf("no descriptor at %s: this linked worktree of an adopted repository has not been initialised — run: wt init", dpath)
		}
		return Env{}, fmt.Errorf("checking %s: %w", dpath, err)
	}
	d, err := readDescriptor(dpath)
	if err != nil {
		return Env{}, err
	}
	return d.env(SourceDescriptor, dpath, explicit), nil
}

// fullySupplied reports whether the caller's explicit values cover every
// resource — the short-circuit of B18.2.
func fullySupplied(explicit map[string]string) bool {
	for _, name := range resourceNames {
		if _, ok := explicit[name]; !ok {
			return false
		}
	}
	return true
}

// findSpec walks up from the process cwd to the worktree root — the first
// directory that contains a wt.yaml — and stops there. An empty specPath
// means the repository has not adopted the tooling.
func findSpec() (root, specPath string, err error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", "", fmt.Errorf("determining the working directory: %w", err)
	}
	for {
		candidate := filepath.Join(dir, "wt.yaml")
		if fi, err := os.Stat(candidate); err == nil && !fi.IsDir() {
			return dir, candidate, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", "", nil
		}
		dir = parent
	}
}

// linkedWorktree reports whether dir is a linked worktree: --git-dir and
// --git-common-dir differ. git is the repo's own tool — the reader's
// constraint is that wt itself need not be installed. A directory that git
// cannot classify (not a repository, or git missing) is not a linked
// worktree: row 1, legacy default.
func linkedWorktree(dir string) bool {
	gitDir, err1 := gitOut(dir, "rev-parse", "--git-dir")
	commonDir, err2 := gitOut(dir, "rev-parse", "--git-common-dir")
	if err1 != nil || err2 != nil {
		return false
	}
	return !samePath(dir, gitDir, commonDir)
}

func gitOut(dir string, args ...string) (string, error) {
	cmd := exec.Command("git", args...)
	cmd.Dir = dir
	out, err := cmd.Output()
	if err != nil {
		return "", err
	}
	return strings.TrimSpace(string(out)), nil
}

// samePath compares two git-reported paths — relative to dir — on their
// symlink-resolved forms: on macOS a temp root under /var resolves to
// /private/var, and the plain strings would disagree with git's own
// resolution.
//
// This is the one path comparison that does not call platform.SamePath: the
// generated reader ships into the user's repository and imports nothing
// outside the standard library.
func samePath(dir, a, b string) bool {
	abs := func(p string) string {
		if filepath.IsAbs(p) {
			return filepath.Clean(p)
		}
		return filepath.Clean(filepath.Join(dir, p))
	}
	ra, errA := filepath.EvalSymlinks(abs(a))
	rb, errB := filepath.EvalSymlinks(abs(b))
	if errA == nil && errB == nil {
		return ra == rb
	}
	return abs(a) == abs(b)
}

// --- descriptor reading -------------------------------------------------

// resourceValue is one row of the resolved resource table.
type resourceValue struct {
	Type  string @@BT@@json:"type"@@BT@@
	Value string @@BT@@json:"value"@@BT@@
}

// envDescriptor is the parsed descriptor: the identity fields plus the
// resolved resources. The reader refuses a schema version it does not
// understand rather than reading the fields it recognises.
type envDescriptor struct {
	Version    int
	App        string
	Slug       string
	Slot       int
	Path       string
	Standalone bool
	Resources  map[string]resourceValue
}

// env renders the resolution result: the descriptor's values, with the
// caller's explicit values overlaid — flags are the highest precedence.
func (d *envDescriptor) env(source Source, path string, explicit map[string]string) Env {
	e := Env{
		App: d.App, Slug: d.Slug, Slot: d.Slot, Path: d.Path, Standalone: d.Standalone,
		Resources: make(map[string]string, len(d.Resources)+len(explicit)),
		Source:    source, EnvPath: path,
	}
	for name, r := range d.Resources {
		e.Resources[name] = r.Value
	}
	for name, v := range explicit {
		e.Resources[name] = v
	}
	return e
}

// readDescriptor reads and parses the descriptor at path in the format the
// spec declared — never sniffed. A newer schema version is refused naming
// the upgrade; a descriptor that will not parse is refused whole, so it is
// never read selectively (05-delivery.md §8).
func readDescriptor(path string) (*envDescriptor, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("reading %s: %w", path, err)
	}
	var d *envDescriptor
	switch DescriptorFormat {
	case "yaml":
		d, err = parseYAMLDescriptor(data)
	case "json":
		d, err = parseJSONDescriptor(data)
	default:
		return nil, fmt.Errorf("parsing %s: unknown descriptor format %q", path, DescriptorFormat)
	}
	if err != nil {
		return nil, fmt.Errorf("parsing %s: %w", path, err)
	}
	if d.Version == 0 {
		return nil, fmt.Errorf("parsing %s: version is required", path)
	}
	if d.Version > 1 {
		return nil, fmt.Errorf("parsing %s: descriptor schema version %d is newer than this reader understands (version 1); regenerate the reader from the spec (or upgrade wt), then re-run", path, d.Version)
	}
	if d.Version != 1 {
		return nil, fmt.Errorf("parsing %s: unsupported descriptor schema version %d (version 1 is the only version this reader understands)", path, d.Version)
	}
	return d, nil
}

// parseJSONDescriptor decodes a json-format descriptor strictly: unknown
// fields are refused whole, like the yaml reader refuses them.
func parseJSONDescriptor(data []byte) (*envDescriptor, error) {
	var raw struct {
		Version    int    @@BT@@json:"version"@@BT@@
		App        string @@BT@@json:"app"@@BT@@
		Slug       string @@BT@@json:"slug"@@BT@@
		Slot       int    @@BT@@json:"slot"@@BT@@
		Path       string @@BT@@json:"path"@@BT@@
		Standalone bool   @@BT@@json:"standalone"@@BT@@
		Resources  map[string]struct {
			Type  string @@BT@@json:"type"@@BT@@
			Value any    @@BT@@json:"value"@@BT@@
		} @@BT@@json:"resources"@@BT@@
		Description string         @@BT@@json:"description"@@BT@@
		State       map[string]any @@BT@@json:"state"@@BT@@
		Shared      []any          @@BT@@json:"shared"@@BT@@
		Extras      map[string]any @@BT@@json:"extras"@@BT@@
	}
	dec := json.NewDecoder(bytes.NewReader(data))
	dec.DisallowUnknownFields()
	if err := dec.Decode(&raw); err != nil {
		return nil, err
	}
	d := &envDescriptor{
		Version: raw.Version, App: raw.App, Slug: raw.Slug, Slot: raw.Slot,
		Path: raw.Path, Standalone: raw.Standalone,
		Resources: make(map[string]resourceValue, len(raw.Resources)),
	}
	for name, r := range raw.Resources {
		d.Resources[name] = resourceValue{Type: r.Type, Value: scalarString(r.Value)}
	}
	return d, nil
}

// parseYAMLDescriptor parses a yaml-format descriptor with the YAML subset
// this reader owns: block mappings and block sequences over quoted and
// plain scalars — exactly what the wt emitter writes — and nothing else.
// The subset is deliberate: this reader is copied into an adopted
// repository and must parse with the standard library alone, so no YAML
// module may be added to the repo's dependencies for the sake of the tool.
// Anything outside the subset is refused with the line number.
func parseYAMLDescriptor(data []byte) (*envDescriptor, error) {
	root, err := yamlValue(string(data))
	if err != nil {
		return nil, err
	}
	m, ok := root.(map[string]any)
	if !ok {
		return nil, fmt.Errorf("the descriptor must be a mapping")
	}
	known := map[string]bool{
		"version": true, "app": true, "slug": true, "slot": true, "path": true,
		"standalone": true, "description": true, "resources": true,
		"state": true, "shared": true, "extras": true,
	}
	for k := range m {
		if !known[k] {
			return nil, fmt.Errorf("unknown field %q — a field from a newer schema version is refused whole, never read selectively", k)
		}
	}
	d := &envDescriptor{Resources: map[string]resourceValue{}}
	if v, ok := m["version"]; ok {
		d.Version, err = intScalar("version", v)
		if err != nil {
			return nil, err
		}
	}
	if v, ok := m["app"]; ok {
		d.App, err = stringScalar("app", v)
		if err != nil {
			return nil, err
		}
	}
	if v, ok := m["slug"]; ok {
		d.Slug, err = stringScalar("slug", v)
		if err != nil {
			return nil, err
		}
	}
	if v, ok := m["slot"]; ok {
		d.Slot, err = intScalar("slot", v)
		if err != nil {
			return nil, err
		}
	}
	if v, ok := m["path"]; ok {
		d.Path, err = stringScalar("path", v)
		if err != nil {
			return nil, err
		}
	}
	if v, ok := m["standalone"]; ok {
		d.Standalone, err = boolScalar("standalone", v)
		if err != nil {
			return nil, err
		}
	}
	if raw, ok := m["resources"]; ok {
		rm, ok := raw.(map[string]any)
		if !ok {
			return nil, fmt.Errorf("resources must be a mapping of resource name to {type, value}")
		}
		for name, rv := range rm {
			entry, ok := rv.(map[string]any)
			if !ok {
				return nil, fmt.Errorf("resource %q must be a mapping of {type, value}", name)
			}
			for k := range entry {
				if k != "type" && k != "value" {
					return nil, fmt.Errorf("resource %q: unknown field %q", name, k)
				}
			}
			typ, err := stringScalar("type", entry["type"])
			if err != nil {
				return nil, fmt.Errorf("resource %q: %w", name, err)
			}
			d.Resources[name] = resourceValue{Type: typ, Value: scalarString(entry["value"])}
		}
	}
	return d, nil
}

func intScalar(field string, v any) (int, error) {
	i, ok := v.(int64)
	if !ok {
		return 0, fmt.Errorf("%s must be an integer, got %v", field, v)
	}
	return int(i), nil
}

func stringScalar(field string, v any) (string, error) {
	s, ok := v.(string)
	if !ok {
		return "", fmt.Errorf("%s must be a string, got %v", field, v)
	}
	return s, nil
}

func boolScalar(field string, v any) (bool, error) {
	b, ok := v.(bool)
	if !ok {
		return false, fmt.Errorf("%s must be true or false, got %v", field, v)
	}
	return b, nil
}

// scalarString renders any scalar the descriptor carries as the string an
// entry point reads: a port as "4203", a namespace as itself.
func scalarString(v any) string {
	switch x := v.(type) {
	case string:
		return x
	case int64:
		return strconv.FormatInt(x, 10)
	case bool:
		return strconv.FormatBool(x)
	case nil:
		return ""
	default:
		return fmt.Sprint(x)
	}
}

// --- the YAML subset parser ---------------------------------------------

type yamlLine struct {
	indent int
	text   string
	number int // 1-based
}

// yamlLines splits a document into significant lines: blank lines and
// comments are skipped, indentation is counted in spaces (a tab in the
// indentation is refused), and CRLF is tolerated.
func yamlLines(data string) ([]yamlLine, error) {
	var out []yamlLine
	for i, raw := range strings.Split(strings.ReplaceAll(data, "\r\n", "\n"), "\n") {
		trimmed := strings.TrimSpace(raw)
		if trimmed == "" || strings.HasPrefix(trimmed, "#") {
			continue
		}
		indent := len(raw) - len(strings.TrimLeft(raw, " "))
		if strings.Contains(raw[:indent], "\t") {
			return nil, fmt.Errorf("line %d: tabs are not allowed in indentation", i+1)
		}
		out = append(out, yamlLine{indent: indent, text: trimmed, number: i + 1})
	}
	return out, nil
}

type yamlParser struct {
	lines []yamlLine
	pos   int
}

// yamlValue parses one document of the subset into a generic tree:
// map[string]any for block mappings, []any for block sequences, and
// string, int64, bool or nil scalars.
func yamlValue(data string) (any, error) {
	lines, err := yamlLines(data)
	if err != nil {
		return nil, err
	}
	if len(lines) == 0 {
		return nil, fmt.Errorf("empty document")
	}
	p := &yamlParser{lines: lines}
	return p.node(lines[0].indent)
}

// node parses the block at the given indentation: a sequence when its
// first line is a dash item, a mapping otherwise.
func (p *yamlParser) node(indent int) (any, error) {
	if p.pos >= len(p.lines) {
		return nil, fmt.Errorf("line %d: unexpected end of document", p.lastNumber())
	}
	if strings.HasPrefix(p.lines[p.pos].text, "-") {
		return p.sequence(indent)
	}
	return p.mapping(indent)
}

func (p *yamlParser) lastNumber() int {
	if len(p.lines) == 0 {
		return 1
	}
	return p.lines[len(p.lines)-1].number
}

// mapping parses a block mapping at the given indentation. A line with
// less indentation belongs to the caller; anything else at the wrong
// indentation is refused.
func (p *yamlParser) mapping(indent int) (map[string]any, error) {
	m := map[string]any{}
	for p.pos < len(p.lines) {
		ln := p.lines[p.pos]
		if ln.indent < indent {
			break
		}
		if ln.indent > indent {
			return nil, fmt.Errorf("line %d: unexpected indentation", ln.number)
		}
		if strings.HasPrefix(ln.text, "-") {
			return nil, fmt.Errorf("line %d: sequence item where a mapping entry was expected", ln.number)
		}
		key, rest, err := splitKey(ln)
		if err != nil {
			return nil, err
		}
		if _, dup := m[key]; dup {
			return nil, fmt.Errorf("line %d: duplicate key %q", ln.number, key)
		}
		p.pos++
		if rest == "" {
			if p.pos >= len(p.lines) {
				return nil, fmt.Errorf("line %d: key %q has no value", ln.number, key)
			}
			child, err := p.node(p.lines[p.pos].indent)
			if err != nil {
				return nil, err
			}
			m[key] = child
			continue
		}
		v, err := yamlScalar(rest, ln.number)
		if err != nil {
			return nil, err
		}
		m[key] = v
	}
	return m, nil
}

// sequence parses a block sequence at the given indentation. Items are
// scalars or mappings; a mapping item's first key rides on the dash line
// and the rest of its keys sit at indent+2.
func (p *yamlParser) sequence(indent int) ([]any, error) {
	var items []any
	for p.pos < len(p.lines) {
		ln := p.lines[p.pos]
		if ln.indent < indent {
			break
		}
		if ln.indent > indent {
			return nil, fmt.Errorf("line %d: unexpected indentation", ln.number)
		}
		if !strings.HasPrefix(ln.text, "-") {
			// The sequence sits at its parent key's own indentation (the
			// emitter's shape), so a sibling mapping key arrives at the
			// sequence's indent: the sequence is over, and the caller's
			// mapping loop owns the line.
			break
		}
		rest := strings.TrimSpace(strings.TrimPrefix(ln.text, "-"))
		if rest == "" {
			p.pos++
			child, err := p.node(indent + 2)
			if err != nil {
				return nil, err
			}
			items = append(items, child)
			continue
		}
		if key, value, isKey := splitKeyText(rest, ln.number); isKey {
			item := map[string]any{}
			if value == "" {
				p.pos++
				if p.pos >= len(p.lines) {
					return nil, fmt.Errorf("line %d: key %q has no value", ln.number, key)
				}
				child, err := p.node(p.lines[p.pos].indent)
				if err != nil {
					return nil, err
				}
				item[key] = child
			} else {
				v, err := yamlScalar(value, ln.number)
				if err != nil {
					return nil, err
				}
				item[key] = v
				p.pos++
			}
			// The rest of the item's mapping, if any: keys at indent+2
			// that are not themselves sequence items.
			for p.pos < len(p.lines) &&
				p.lines[p.pos].indent == indent+2 &&
				!strings.HasPrefix(p.lines[p.pos].text, "-") {
				kln := p.lines[p.pos]
				k, r, err := splitKey(kln)
				if err != nil {
					return nil, err
				}
				p.pos++
				if r == "" {
					if p.pos >= len(p.lines) {
						return nil, fmt.Errorf("line %d: key %q has no value", kln.number, k)
					}
					child, err := p.node(p.lines[p.pos].indent)
					if err != nil {
						return nil, err
					}
					item[k] = child
					continue
				}
				v, err := yamlScalar(r, kln.number)
				if err != nil {
					return nil, err
				}
				item[k] = v
			}
			items = append(items, item)
			continue
		}
		v, err := yamlScalar(rest, ln.number)
		if err != nil {
			return nil, err
		}
		items = append(items, v)
		p.pos++
	}
	return items, nil
}

// splitKey splits a mapping line into its key and the rest after the
// separator. The separator is the first ": " or a trailing ":"; a quoted
// key is unquoted, a plain key must look like one.
func splitKey(ln yamlLine) (key, rest string, err error) {
	key, rest, isKey := splitKeyText(ln.text, ln.number)
	if !isKey {
		return "", "", fmt.Errorf("line %d: expected a key: value entry, got %q", ln.number, ln.text)
	}
	return key, rest, nil
}

// splitKeyText implements splitKey over any text (a mapping line, or the
// rest of a dash line). isKey is false when the text is not a key: value
// entry at all.
func splitKeyText(text string, number int) (key, rest string, isKey bool) {
	sep := -1
	if strings.HasSuffix(text, ":") {
		sep = len(text) - 1
	} else if i := strings.Index(text, ": "); i >= 0 {
		sep = i
	}
	if sep < 0 {
		return "", "", false
	}
	raw := text[:sep]
	rest = text[sep+1:]
	if strings.HasPrefix(rest, ":") {
		rest = rest[1:]
	}
	rest = strings.TrimSpace(rest)
	if strings.HasPrefix(raw, @@BT@@"@@BT@@) {
		key, err := strconv.Unquote(raw)
		if err != nil {
			return "", "", false
		}
		return key, rest, true
	}
	if raw == "" || strings.ContainsAny(raw, " \t") {
		return "", "", false
	}
	return raw, rest, true
}

// yamlScalar parses a scalar value: a double-quoted string, or one of the
// plain scalars the emitter writes — an integer, true, false or null.
// Anything else is refused with the line number: the descriptor is written
// by wt, and a hand-edited value outside the subset is refused rather than
// guessed at.
func yamlScalar(text string, number int) (any, error) {
	if strings.HasPrefix(text, @@BT@@"@@BT@@) {
		v, err := strconv.Unquote(text)
		if err != nil {
			return nil, fmt.Errorf("line %d: malformed quoted string: %v", number, err)
		}
		return v, nil
	}
	switch text {
	case "true":
		return true, nil
	case "false":
		return false, nil
	case "null", "~":
		return nil, nil
	case "{}":
		// The emitter writes an empty mapping for an absent section
		// (state: {}, extras: {}): the empty flow form is part of the
		// subset.
		return map[string]any{}, nil
	case "[]":
		return []any{}, nil
	}
	if i, err := strconv.ParseInt(text, 10, 64); err == nil {
		return i, nil
	}
	return nil, fmt.Errorf("line %d: unsupported scalar %q — the descriptor must be written by wt (quoted strings, integers, true, false and null are the only scalars)", number, text)
}
`
